package com.automark.service;
import com.automark.connector.*; import com.automark.domain.*; import com.automark.web.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class LookupService {
 private final LookupRepository lookups; private final VehicleRepository vehicles; private final SourceQueryRepository queries; private final RawSourceDataRepository raw; private final VehicleFactRepository facts; private final ReportFlagRepository flags; private final SourceSelectionService selection; private final List<FactNormalizer> normalizers; private final MileageRollbackDetector rollback;
 public LookupService(LookupRepository l,VehicleRepository v,SourceQueryRepository q,RawSourceDataRepository r,VehicleFactRepository f,ReportFlagRepository fl,SourceSelectionService s,List<FactNormalizer> n,MileageRollbackDetector d){lookups=l;vehicles=v;queries=q;raw=r;facts=f;flags=fl;selection=s;normalizers=n;rollback=d;}
 @Transactional public LookupResponse execute(CreateLookupRequest request){LookupType type=request.inputType();String value=normalize(request.value(),type);String country=request.countryHint()==null?null:request.countryHint().toUpperCase();Lookup lookup=new Lookup(type,value,country);Vehicle vehicle=findOrCreate(type,value,country);lookup.setVehicle(vehicle);lookups.save(lookup);List<VehicleSourceConnector> selected=selection.select(new LookupInput(type,value,country));for(VehicleSourceConnector connector:selected)runConnector(lookup,vehicle,connector,new LookupInput(type,value,country));if(selected.isEmpty())lookup.fail();else lookup.complete();lookups.save(lookup);refreshFlags(vehicle);return response(lookup);}
 private Vehicle findOrCreate(LookupType type,String value,String country){if(type==LookupType.VIN)return vehicles.findByVin(value).orElseGet(()->vehicles.save(new Vehicle(value,null,country)));return vehicles.findByPrimaryPlateAndPrimaryCountry(value,country==null?"NL":country).orElseGet(()->vehicles.save(new Vehicle(null,value,country==null?"NL":country)));}
 private void runConnector(Lookup lookup,Vehicle vehicle,VehicleSourceConnector connector,LookupInput input){SourceQuery query=queries.save(new SourceQuery(lookup,connector.sourceId()));SourceFetchResult result=connector.fetch(input);query.finish(result.status(),result.errorMessage());queries.save(query);if(result.rawPayload()==null)return;raw.save(new RawSourceData(query,result.rawPayload()));FactNormalizer normalizer=normalizers.stream().filter(n->n.sourceId().equals(connector.sourceId())||connector.sourceId().startsWith(n.sourceId())).findFirst().orElse(null);if(normalizer==null)return;for(FactCandidate candidate:normalizer.normalize(result.rawPayload()))facts.save(new VehicleFact(vehicle,candidate.type(),candidate.value(),candidate.observedAt(),connector.sourceId(),query,candidate.confidence()));}
 private void refreshFlags(Vehicle vehicle){flags.deleteByVehicleId(vehicle.getId());flags.saveAll(rollback.detect(vehicle,facts.findByVehicleId(vehicle.getId())));}
 @Transactional(readOnly=true) public LookupResponse response(UUID lookupId){return response(lookups.findById(lookupId).orElseThrow(()->new NotFoundException("Lookup not found")));}
 private LookupResponse response(Lookup lookup){return new LookupResponse(lookup.getId(),lookup.getStatus(),lookup.getVehicle().getId(),lookup.getCreatedAt());}
 private String normalize(String value,LookupType type){String pattern=type==LookupType.VIN?"[^A-Z0-9]":"[\\s-]";String normalized=value.trim().toUpperCase().replaceAll(pattern,"");if(normalized.isBlank())throw new IllegalArgumentException("Lookup value is required");return normalized;}
}
