spring:
  application.name: TaxCalculator
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/taxcalculator}
    username: ${DATABASE_USERNAME:taxcalculator}
    password: ${DATABASE_PASSWORD:taxcalculator}
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
  jpa:
    hibernate.ddl-auto: validate
    open-in-view: false
  jackson:
    default-property-inclusion: non_null
server:
  port: ${PORT:8080}
